# Generated by Django 3.0.6 on 2020-05-30 16:58

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('graduacao', models.CharField(max_length=100, verbose_name='Graduação')),
                ('texto', models.TextField(max_length=500, verbose_name='Obsevações')),
                ('imagem', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Foto')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da publicação')),
            ],
        ),
        migrations.AlterField(
            model_name='atletas',
            name='graduacao',
            field=models.CharField(max_length=100, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='texto',
            field=models.TextField(max_length=500, verbose_name='Obsevações'),
        ),
    ]
