# Generated by Django 3.0.6 on 2020-05-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0002_auto_20200530_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atletas',
        ),
    ]
