# Generated by Django 3.0.6 on 2020-05-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0003_delete_atletas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Atletas',
        ),
    ]
