# Generated by Django 3.0.6 on 2020-05-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0004_auto_20200530_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atletas',
            new_name='Atleta',
        ),
    ]
