# Generated by Django 3.0.6 on 2020-05-31 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0008_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='graduacao',
        ),
        migrations.AddField(
            model_name='atleta',
            name='faixa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coreZion.Faixa'),
            preserve_default=False,
        ),
    ]
