# Generated by Django 3.0.6 on 2020-05-31 19:55

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0009_auto_20200530_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
            ],
            options={
                'verbose_name_plural': 'Atas',
            },
        ),
        migrations.AlterModelOptions(
            name='atleta',
            options={'verbose_name_plural': 'Atletas'},
        ),
    ]
