# Generated by Django 3.0.6 on 2020-05-31 20:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0010_auto_20200531_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='autor',
            field=models.CharField(default=1, max_length=50, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ata',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
    ]
