# Generated by Django 3.0.6 on 2020-06-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0012_auto_20200603_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_atleta',
            name='id',
        ),
        migrations.AddField(
            model_name='ficha_atleta',
            name='diretores',
            field=models.CharField(choices=[('DIRETO', 'FINANCIRO'), ('DIRETO', 'ESPORTE'), ('DIRETO', 'GERAL')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha_atleta',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
    ]
