# Generated by Django 3.0.6 on 2020-06-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0013_auto_20200603_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ficha_atleta',
            name='diretores',
            field=models.CharField(choices=[('FINANCIRO', 'FINANCEIRO'), ('ESPORTE', 'ESPORTE'), ('GERAL', 'GERAL')], max_length=9, verbose_name='Diretor'),
        ),
    ]
