# Generated by Django 3.0.6 on 2020-06-11 17:03

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0014_auto_20200606_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atleta',
            options={'verbose_name_plural': 'Alunos'},
        ),
        migrations.CreateModel(
            name='cadastro_atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=11, verbose_name='Nome')),
                ('nomesobre', models.CharField(max_length=100, verbose_name='Nome Copleto')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('pai', models.CharField(max_length=100, verbose_name='Nome do Pai')),
                ('data_nasci', models.CharField(max_length=10, verbose_name='Data do Nascimento')),
                ('endereco', models.CharField(max_length=254, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro que mora')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP da Rua')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('tele_resp', models.CharField(max_length=15, verbose_name='Telefone do Resposável')),
                ('email_federa', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('quan_pesso', models.CharField(max_length=2, verbose_name='Familiares Qunt.')),
                ('tipo_sang', models.CharField(choices=[('TIPO SANGUE', 'A+'), ('TIPO SANGUE', 'A-'), ('TIPO SANGUE', 'B+'), ('TIPO SANGUE', 'B-'), ('TIPO SANGUE', 'AB+'), ('TIPO SANGUE', 'AB-'), ('TIPO SANGUE', 'O+'), ('TIPO SANGUE', 'O-'), ('TIPO SANGUE', 'FATOR Rh+'), ('TIPO SANGUE', 'FATOR Rh-')], max_length=12, verbose_name='Tipo sangue')),
                ('cartao_sus', models.CharField(max_length=100, verbose_name='Cartão do SUS')),
                ('escolaridade', models.CharField(choices=[('EDUCAÇÃO INFATIL', 'EDUCAÇÃO INFANTIL'), ('ENSINO FUNDAMENTAL', 'ENSINO FUNDAMENTAL'), ('ENSINO MÉDIO', 'ENSINO MÉDIO')], max_length=20, verbose_name='Escolaridade')),
                ('serie', models.CharField(max_length=100, verbose_name='Série ano letivo')),
                ('nome_escola', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('unidade_treino', models.CharField(choices=[('ULISSES GUIMARÃES', 'ULISSES GUIMARÃES'), ('AYRTON SENNA', 'AYRTON SENNA'), ('FLORESTA', 'FLORESTA')], max_length=20, verbose_name='Unidade de Treino')),
                ('renda_fami', models.CharField(choices=[('ATE 1 SALARIO MÍNIMO', 'ATE 1 SALARIO MÍNIMO'), ('DE 1 A 2 SALARIOAS MÍNIMOS', 'DE 1 A 2 SALARIOAS MÍNIMOS'), ('DE 2 A 4 SALARIOAS MÍNIMOS', 'DE 2 A 4 SLARIOS MÍNIMOS'), ('ACIMA DE 5 SLARIOS MÍNIMOS', 'ACIMA DE 5 SLARIOS MÍNIMOS')], max_length=28, verbose_name='Renda Familiar')),
                ('peso', models.CharField(max_length=6, verbose_name='Peso Atual')),
                ('texto', models.TextField(max_length=500, verbose_name='Obsevações')),
                ('imagem', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Foto')),
                ('diretores', models.CharField(choices=[('FINANCIRO', 'FINANCEIRO'), ('ESPORTE', 'ESPORTE'), ('GERAL', 'GERAL')], max_length=9, verbose_name='Diretor')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
                ('active', models.BooleanField(default=True)),
                ('faixas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreZion.Faixa')),
            ],
            options={
                'verbose_name_plural': 'Atletas',
            },
        ),
    ]
