# Generated by Django 3.0.6 on 2020-06-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0015_auto_20200611_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_atleta',
            name='numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Numero casa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='nomesobre',
            field=models.CharField(max_length=11, verbose_name='Nome Copleto'),
        ),
    ]
