# Generated by Django 3.0.6 on 2020-06-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0016_auto_20200613_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='data_nasci',
            field=models.CharField(max_length=12, verbose_name='Data do Nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='faixas',
            field=models.CharField(max_length=50, verbose_name='Cor da Faixa'),
        ),
    ]
