# Generated by Django 3.0.6 on 2020-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0017_auto_20200614_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='diretores',
            field=models.CharField(max_length=50, verbose_name='Diretor'),
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='escolaridade',
            field=models.CharField(max_length=20, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='renda_fami',
            field=models.CharField(max_length=28, verbose_name='Renda Familiar'),
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='tipo_sang',
            field=models.CharField(max_length=12, verbose_name='Tipo sangue'),
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='unidade_treino',
            field=models.CharField(max_length=20, verbose_name='Unidade de Treino'),
        ),
    ]
