# Generated by Django 3.0.6 on 2020-06-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0018_auto_20200614_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='renda_fami',
            field=models.CharField(max_length=50, verbose_name='Renda Familiar'),
        ),
    ]
