# Generated by Django 3.0.6 on 2020-06-23 02:06

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0019_auto_20200614_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
            ],
        ),
        migrations.AlterField(
            model_name='cadastro_atleta',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Ficha_Atleta',
        ),
    ]
