# Generated by Django 3.0.6 on 2020-06-26 01:23

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0020_auto_20200622_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
            ],
        ),
    ]
