# Generated by Django 3.0.6 on 2020-07-06 00:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0022_diretoria_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descrição')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
            ],
        ),
    ]
