# Generated by Django 3.0.6 on 2020-07-14 02:18

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreZion', '0025_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen1', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 1')),
                ('imagen2', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 2')),
                ('imagen3', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 3')),
                ('imagen4', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 4')),
                ('imagen5', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 5')),
                ('imagen6', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 6')),
                ('imagen7', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 7')),
                ('imagen8', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 8')),
                ('imagen9', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 9')),
                ('imagen10', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 10')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
            ],
        ),
    ]
